{
    "input": {
      "input_file_name": "dimuon_LHC2017.root",
      "input_name": "hInvMassPt612",
      "pdf_dictionary": {
        "pdf": ["CB2", "CB2", "Pol4Exp", "SUM"],
        "pdfName": ["Jpsi", "Psi2s", "polexp", "SUM"],
        "pdfColor": [861, 417, 1],
        "pdfNameForLegend": ["J/#psi", "Background", "Fit"],
        "pdfStyle": [1, 1, 2],
        "parFix": [
        [False, False, True, True, True, True],
        [False, False, True, True, True, True],
        [False, False, False, False, False, False],
        [False, False, False]
      ],
        "parVal": [
          [3.096, 1.2e-01, 1.089, 3.393, 2.097, 8.694],
          [3.68, 1.5e-01, 1.089, 3.393, 2.097, 8.694],
          [1, 1, 1, 1, 1, 1],
          [1000, 100, 100000]
        ],
        "parLimMin": [
          [2.9, 7.0e-02, 1.0889, 3.3929, 2.096, 8.693],
          [3.2, 7.0e-02, 1.0889, 3.3929, 2.096, 8.693],
          [-100, -100, -100, -100, -100, -100],
          [0, 0, 0]
        ],
        "parLimMax": [
          [3.5, 1.9e-01, 1.0891, 3.3931, 2.098, 8.695],
          [3.9, 1.9e-01, 1.0891, 3.3931, 2.098, 8.695],
          [100, 100, 100, 100, 100, 100],
          [50000, 5000, 500000]
        ],
        "parName": [
          ["mean_Jpsi", "width_Jpsi", "a_Jpsi", "b_Jpsi", "c_Jpsi", "d_Jpsi"],
          ["sum::mean_Psi2s(mean_Jpsi,0.584)", "prod::width_Psi2s(width_Jpsi,1.05)", "a_Psi2s", "b_Psi2s", "c_Psi2s", "d_Psi2s"],
          ["aa", "bb", "cc","dd", "ee", "ff"],
          ["sig_Jpsi", "sig_Psi2s", "bkg"]
        ],
        "fitRangeMin": [2, 2.1, 2.2],
        "fitRangeMax": [5, 4.9, 4.8],
        "fitMethod": "likelyhood",
        "doResidualPlot": true,
        "doPullPlot": true, 
        "doCorrMatPlot": true,
        "doAlicePlot": true,
        "parForAlicePlot": ["mean_Jpsi", "width_Jpsi", "sig_Jpsi"],
        "parNameForAlicePlot": ["#mu_{J/#psi}", "#sigma_{J/#psi}", "#it{N}_{J/#psi}"],
        "text": [
          [0.20, 0.87, "LHC17 CB2+Pol4EXP, #sqrt{#it{s}} = 5.02 TeV"], 
          [0.20, 0.80, "2.5 < #it{y} < 4, J/#psi #rightarrow #mu^{+}#mu^{-}"]
        ]
      }
    },
    "output": {
      "output_file_name": "/Users/valencia/Desktop/dq_fit_library/validation/output/"
      
      
    }
  }
