{
  "input": {
    "input_file_name": "SumHistos_161718.root",
    "input_name": "hMassOS_CMUL7",
    "pdf_dictionary": {
      "pdf": ["CB2", "CB2", "CB2", "VWG", "SUM"],
      "pdfName": ["Upsilon1s", "Upsilon2s", "Upsilon3s", "Bkg", "SUM"],
      "pdfColor": [861, 417, 2, 1],
      "pdfNameForLegend": ["#Upsilon(1S)", "#Upsilon(2S)", "#Upsilon(3S)", "Background", "Fit"],
      "pdfStyle": [1, 1, 1, 2],
      "parFix": [
        [False, False, True, True, True, True],
        [False, False, True, True, True, True],
        [False, False, True, True, True, True],
        [False, False, False],
        [False, False, False]
      ],
      "parVal": [
        [9.4603, 0.15, 1.016, 2.035, 2.063, 2.247],
        [10.0233, 0.134, 1.016, 2.035, 2.063, 2.247],
        [10.3552, 0.139, 1.016, 2.035, 2.063, 2.247],
        [1, 1, 1],
        [10000, 500, 100, 100000]
      ],
      "parLimMin": [
        [9.1,  0.1, 1.01, 2.032, 2.060, 2.245],
        [9.7, 0.03, 1.01, 2.032, 2.060, 2.245],
        [10., 0.04, 1.01, 2.032, 2.060, 2.245],
        [-10, 0, -100],
        [0, 0, 0, 0]
      ],
      "parLimMax": [
        [9.7, 0.2,  1.018, 2.037, 2.065, 2.249],
        [10.3, 0.2,  1.018, 2.037, 2.065, 2.249],
        [10.5, 0.2, 1.018, 2.037, 2.065, 2.249],
        [10, 100, 100],
        [500000,10000, 5000, 500000]
      ],
      "parName": [
        ["mean_Upsilon1s", "width_Upsilon1s", "a_Upsilon1s", "b_Upsilon1s", "c_Upsilon1s", "d_Upsilon1s"],
        ["sum::mean_Upsilon2s(mean_Upsilon1s,0.5630)", "prod::width_Upsilon2s(width_Upsilon1s,1.0495)", "a_#Upsilon_2s", "b_#Upsilon2s", "c_#Upsilon2s", "d_#Upsilon2s"],
        ["sum::mean_Upsilon3s(mean_Upsilon1s,0.8949)", "prod::width_Upsilon3s(width_Upsilon1s,1.0794)", "a_#Upsilon_3s", "b_#Upsilon3s", "c_#Upsilon3s", "d_#Upsilon3s"],
        ["aa", "bb", "cc"],
        ["sig_Upsilon1s","sig_Upsilon2s", "sig_Upsilon3s", "bkg"]
      ],
      "fitRangeMin": [7, 7.1, 7.2],
      "fitRangeMax": [12, 11.9, 11.8],
      "fitMethod": "likelyhood",
      "doResidualPlot": true,
      "doPullPlot": true, 
      "doCorrMatPlot": true,
      "doAlicePlot": true,
      "parForAlicePlot": ["mean_Upsilon1s", "width_Upsilon1s", "sig_Upsilon1s","sig_Upsilon2s","sig_Upsilon3s"],
      "parNameForAlicePlot": ["#mu_{#Upsilon(1S)}", "#sigma_{#Upsilon(1S)}", "#it{N}_{#Upsilon(1S)}", "#it{N}_{#Upsilon(2S)}", "#it{N}_{#Upsilon(3S)}"],
      "text": [
        [0.20, 0.87, "LHC16-17-18 CB2+VWG, #sqrt{#it{s}} = 13 TeV"],  
        [0.20, 0.80, "2.5 < #it{y} < 4, #Upsilon #rightarrow #mu^{+}#mu^{-}"]
      ]
    }
  },
  "output": {
    
    
    "output_file_name": "/Users/valencia/Desktop/dq_fit_library/validation/output/"
  }
}
